# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serverToClient.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='serverToClient.proto',
  package='addressbook',
  syntax='proto3',
  serialized_pb=_b('\n\x14serverToClient.proto\x12\x0b\x61\x64\x64ressbook\"\"\n\x04\x62oss\x12\n\n\x02hp\x18\x01 \x01(\x05\x12\x0e\n\x06\x61ttack\x18\x02 \x01(\x05\"|\n\x06player\x12\n\n\x02hp\x18\x01 \x01(\x05\x1a\x32\n\x03pos\x12\r\n\x05pos_x\x18\x01 \x01(\x11\x12\r\n\x05pos_y\x18\x02 \x01(\x11\x12\r\n\x05pos_z\x18\x03 \x01(\x11\x1a\x32\n\x03rot\x12\r\n\x05rot_x\x18\x01 \x01(\x11\x12\r\n\x05rot_y\x18\x02 \x01(\x11\x12\r\n\x05rot_z\x18\x03 \x01(\x11\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BOSS = _descriptor.Descriptor(
  name='boss',
  full_name='addressbook.boss',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hp', full_name='addressbook.boss.hp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attack', full_name='addressbook.boss.attack', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=71,
)


_PLAYER_POS = _descriptor.Descriptor(
  name='pos',
  full_name='addressbook.player.pos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos_x', full_name='addressbook.player.pos.pos_x', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos_y', full_name='addressbook.player.pos.pos_y', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos_z', full_name='addressbook.player.pos.pos_z', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=145,
)

_PLAYER_ROT = _descriptor.Descriptor(
  name='rot',
  full_name='addressbook.player.rot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rot_x', full_name='addressbook.player.rot.rot_x', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rot_y', full_name='addressbook.player.rot.rot_y', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rot_z', full_name='addressbook.player.rot.rot_z', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=197,
)

_PLAYER = _descriptor.Descriptor(
  name='player',
  full_name='addressbook.player',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hp', full_name='addressbook.player.hp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PLAYER_POS, _PLAYER_ROT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=197,
)

_PLAYER_POS.containing_type = _PLAYER
_PLAYER_ROT.containing_type = _PLAYER
DESCRIPTOR.message_types_by_name['boss'] = _BOSS
DESCRIPTOR.message_types_by_name['player'] = _PLAYER

boss = _reflection.GeneratedProtocolMessageType('boss', (_message.Message,), dict(
  DESCRIPTOR = _BOSS,
  __module__ = 'serverToClient_pb2'
  # @@protoc_insertion_point(class_scope:addressbook.boss)
  ))
_sym_db.RegisterMessage(boss)

player = _reflection.GeneratedProtocolMessageType('player', (_message.Message,), dict(

  pos = _reflection.GeneratedProtocolMessageType('pos', (_message.Message,), dict(
    DESCRIPTOR = _PLAYER_POS,
    __module__ = 'serverToClient_pb2'
    # @@protoc_insertion_point(class_scope:addressbook.player.pos)
    ))
  ,

  rot = _reflection.GeneratedProtocolMessageType('rot', (_message.Message,), dict(
    DESCRIPTOR = _PLAYER_ROT,
    __module__ = 'serverToClient_pb2'
    # @@protoc_insertion_point(class_scope:addressbook.player.rot)
    ))
  ,
  DESCRIPTOR = _PLAYER,
  __module__ = 'serverToClient_pb2'
  # @@protoc_insertion_point(class_scope:addressbook.player)
  ))
_sym_db.RegisterMessage(player)
_sym_db.RegisterMessage(player.pos)
_sym_db.RegisterMessage(player.rot)


# @@protoc_insertion_point(module_scope)
